In [1]:
#1
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.naive_bayes import BernoulliNB, MultinomialNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import numpy as np

In [2]:
#2
import pandas as pd
df_train=pd.read_csv("newsgroups_train.csv")
df_test=pd.read_csv("newsgroups_test.csv")
print("Train:",df_train.shape)
print("Test:",df_test.shape)

Train: (1657, 3)
Test: (1102, 3)


In [3]:
#3&4
#Done in above
#2 Question
#new_train=fetch_20newsgroup(subset='train',categories=cats)
#new_test=fetch_20newsgroup(subset='test',categories=cats)
#if they dont give the dataset dircetly

In [4]:
#5
print("Target Labels:",df_train['category'].unique())

Target Labels: ['sci.space' 'comp.graphics' 'alt.atheism']


In [5]:
#6
#already done in 5th Question

In [6]:
#7
selected_categories=['alt.atheism','comp.graphics','sci.space']
print("Selected Categories:",selected_categories)

Selected Categories: ['alt.atheism', 'comp.graphics', 'sci.space']


In [11]:
#6 to 8 th done in above

#except 3 catgories->filter
#df_test_filter=df_test[df_test['category'].isin(selected_categories)]
#print(df_test_filter.shape)
#print(df_test_filter.head())

In [12]:
#9
print("New_Training Set:",df_train['target'].unique())

New_Training Set: [2 1 0]


In [13]:
#10
print("5th training article:",df_train.iloc[4]['text'])

5th training article: From: henry@zoo.toronto.edu (Henry Spencer)
Subject: Re: TRUE "GLOBE", Who makes it?
Organization: U of Toronto Zoology
Lines: 12

In article <bill.047m@xpresso.UUCP> bill@xpresso.UUCP (Bill Vance) writes:
>It has been known for quite a while that the earth is actually more pear
>shaped than globular/spherical.  Does anyone make a "globe" that is accurate
>as to actual shape, landmass configuration/Long/Lat lines etc.?

I don't think you're going to be able to see the differences from a sphere
unless they are greatly exaggerated.  Even the equatorial bulge is only
about 1 part in 300 -- you'd never notice a 1mm error in a 30cm globe --
and the other deviations from spherical shape are much smaller.
-- 
SVR4 resembles a high-speed collision   | Henry Spencer @ U of Toronto Zoology
between SVR3 and SunOS.    - Dick Dunn  |  henry@zoo.toronto.edu  utzoo!henry



In [14]:
#11
print("Train Data Shape:",df_train.shape,"Test Data Shape:",df_test.shape)

Train Data Shape: (1657, 3) Test Data Shape: (1102, 3)


In [15]:
#12
#not applicable for csv files
#if its not csv
#selected_categories=['alt.atheism','comp.graphics','sci.space']
#newsgroup_train=fetch_20newsgroups(subset='train',categories=selected_categories)
#newsgroup_test=fetch_20newsgroups(subset='test',categories=selected_categories)
#print("training data size:",newsgroup_train.data)
#print("testing data size:",newsgroup_test.data)

In [16]:
#13
vectorizer=CountVectorizer()
X_train_counts=vectorizer.fit_transform(df_train['text'])
X_test_counts=vectorizer.transform(df_test['text'])

In [17]:
#14
br=BernoulliNB()
br.fit(X_train_counts,df_train['target'])

BernoulliNB()

In [18]:
#15
vectorizer=CountVectorizer()
X_train_counts=vectorizer.fit_transform(df_train['text'])
X_test_counts=vectorizer.transform(df_test['text'])
print(X_train_counts.shape,X_test_counts.shape)

(1657, 29663) (1102, 29663)


In [19]:
#16
prediction=br.predict(X_test_counts)

In [20]:
#17
accuracy=accuracy_score(df_test['target'],prediction)
print("Bernoulli Accuracy_score:",accuracy)

Bernoulli Accuracy_score: 0.852994555353902


In [28]:
#18
tfidf_vectorizer=TfidfVectorizer()
X_train_tfidf=tfidf_vectorizer.fit_transform(df_train['text'])
X_test_tfidf=tfidf_vectorizer.transform(df_test['text'])

mlb=MultinomialNB()
mlb.fit(X_train_tfidf,df_train['target'])
prediction_tfidf=mlb.predict(X_test_tfidf)
accuracy_tfidf=accuracy_score(df_test['target'],prediction_tfidf)
print("accuracy_tfidf:",accuracy_tfidf)
print("confusion matrics:\n",confusion_matrix(df_test['target'],prediction_tfidf))
print("classification report:\n",classification_report(df_test['target'],prediction_tfidf))

accuracy_tfidf: 0.9473684210526315
confusion matrics:
 [[303   2  14]
 [  6 357  26]
 [  2   8 384]]
classification report:
               precision    recall  f1-score   support

           0       0.97      0.95      0.96       319
           1       0.97      0.92      0.94       389
           2       0.91      0.97      0.94       394

    accuracy                           0.95      1102
   macro avg       0.95      0.95      0.95      1102
weighted avg       0.95      0.95      0.95      1102



In [39]:
#19
#done

In [29]:
#20
vectorizer=CountVectorizer()
X_train_counts_stop=vectorizer.fit_transform(df_train['text'])
X_test_counts_stop=vectorizer.transform(df_test['text'])

br_stop=BernoulliNB()
br_stop.fit(X_train_counts_stop,df_train['target'])
prediction_stop=br_stop.predict(X_test_counts_stop)
accuracy_stop=accuracy_score(df_test['target'],prediction_stop)
print("accuracy_stop:",accuracy_stop)
print("confusion matrics:\n",confusion_matrix(df_test['target'],prediction_stop))
print("classification report:\n",classification_report(df_test['target'],prediction_stop))

accuracy_stop: 0.852994555353902
confusion matrics:
 [[270  47   2]
 [  5 373  11]
 [  7  90 297]]
classification report:
               precision    recall  f1-score   support

           0       0.96      0.85      0.90       319
           1       0.73      0.96      0.83       389
           2       0.96      0.75      0.84       394

    accuracy                           0.85      1102
   macro avg       0.88      0.85      0.86      1102
weighted avg       0.88      0.85      0.85      1102

